<?php
// $Id$

/**
 * @file
 * M—dulo de trabajo (pruebas) para aprender a desarrollar m—dulos con Drupal 7.
 * 
 * El idioma de los comentarios ser‡ el espa–ol, ya que la audiencia del m—dulo en cuesti—n
 * es que quiera aprender a desarrollar m—dulos de Drupal y que hable espa–ol.
 * Los textos de UI que se integren en el m—dulo deber’an estar en ingles e ir dentro de 
 * funci—n t() tal y como funciona el sistema de i18n de Drupal.
 *
 * La idea de este m—dulo es colaborar en el desarrollo de un m—dulo de Drupal 7 
 * con fines didacticos. De esta manera se podr‡ ver el resultado del trabajo de
 * otros desarrolladores y comparar soluciones.
 */

/**
 * Implements hook_help().
 */
function drupalval_help($path, $arg) {
  if ($path == 'admin/help#drupalval') {
    return t('A demonstration module.');
  }
}

/**
 * Implements hook_block_info().
 */
function drupalval_block_info() {
  $blocks = array();

  $blocks['list_modules'] = array(
    'info' => t('A listing of all of the enabled modules.'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function drupalval_block_view($block_name = '') {
  if ($block_name == 'list_modules') {
    $list = module_list();

    $theme_args = array('items' => $list, 'type' => 'ol');
    $content = theme('item_list', $theme_args);

    $block = array(
      'subject' => t('Enabled Modules'),
      'content' => $content,
    );

    return $block;
  }
}

/**
 * Implementaci—n del hook menu
 */
function drupalval_menu() {
  $items = array();
  
  global $user;
  $myuser_name = $user->name;

  $items['drupalval/pagprueba/%'] = array(
    'title' => 'Prueba @placeholder', 
  	'title arguments' => array('@placeholder' => $myuser_name),
    'page callback' => 'pagprueba',
  	'page arguments' => array(2), 
    'access callback' => TRUE,
  	'type' => MENU_NORMAL_ITEM,
  	'menu_name' => 'navigation',
  );
  
  return $items;
}

/**
 * Callback
 * Devuelve texto de prueba
 */
function pagprueba($myid) {
	return "dkdjskdjksd " . $myid;
}	